version: 2

sources:
  - name: raw
    database: postgres
    schema: raw
    tables:
      - name: players

models:
  - name: stg_players
    columns:
      - name: player_id
        tests:
          - not_null

  - name: int_players
    columns:
      - name: player_id
        tests:
          - not_null
      - name: season
        tests:
          - not_null