{{ config(materialized='incremental', unique_key='PLAYER_ID') }}

SELECT
    "PLAYER_ID",
    "LANE_AGILITY_TIME",
    "MAX_VERTICAL_LEAP",
    "STANDING_VERTICAL_LEAP",
    "THREE_QUARTER_SPRINT",
    "STANDING_REACH_FT_IN",
    "WINGSPAN_FT_IN",
    "WEIGHT",
    "POSITION",
    "FIRST_NAME",
    "LAST_NAME",
    "SEASON",
    "HEIGHT_WO_SHOES_FT_IN",
    "HAND_WIDTH",
    "HAND_LENGTH"
FROM {{ source('raw', 'players') }}
WHERE "PLAYER_ID" != -1
  AND "LANE_AGILITY_TIME" IS NOT NULL
  AND "MAX_VERTICAL_LEAP" IS NOT NULL
  AND "STANDING_VERTICAL_LEAP" IS NOT NULL
  AND "THREE_QUARTER_SPRINT" IS NOT NULL
  AND "STANDING_REACH_FT_IN" IS NOT NULL
  AND "WINGSPAN_FT_IN" IS NOT NULL
  AND "WEIGHT" IS NOT NULL
  AND "POSITION" IS NOT NULL
  AND "FIRST_NAME" IS NOT NULL
  AND "LAST_NAME" IS NOT NULL
  AND "SEASON" IS NOT NULL
  AND "HEIGHT_WO_SHOES_FT_IN" IS NOT NULL
  AND "HAND_WIDTH" IS NOT NULL
  AND "HAND_LENGTH" IS NOT NULL
{% if is_incremental() %}
  AND "PLAYER_ID" > (SELECT MAX("PLAYER_ID") FROM {{ this }})
{% endif %}