

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  ingestion:
    build: ./ingestion
    env_file:
      - .env
    command: python raw.py
    restart: "no"

  nba_dbt:
    build: ./nba_dbt
    env_file:
      - .env
    volumes:
      - ./nba_dbt/target:/app/target
      - ./nba_dbt/logs:/app/logs
    command: dbt run
    restart: "no"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: fd00:dead:beef::/48